steps:
#install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  options:
  logging: CLOUD_LOGGING_ONLY

#Test

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test:unit']

  #Build

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

    #Deploy

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']